version = '0.54.1'

[git]
default-branch = 'main'
message-template = 'Bump version {{.Current}} -> {{.Next}}'
tag-template = 'v{{.Next}}'

[[file]]
path = 'pyproject.toml'
search = 'version = "{{.Current}}"'
